title: My Thoughts
description: This is the space where I share some lines of thinking. Feel free to explore the topics that are poking my brain.
baseurl: /ae87e62189
permalink: /:year/:month/:day/:title.html
excerpt_separator: "<!--more-->"


